# Site settings
site_name: Package Name
site_url: https://www.package-name.com

# Repository settings
repo_name: collier-p-charlie/python-repo-template
repo_url: https://github.com/collier-p-charlie/python-repo-template

# Theme settings
theme:
  name: material
  language: en
  font:
    text: montserrat
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference:
      - Main: main/api.md
