name: Feature Request
description: File a request for a new feature.
title: "[Feature]: "
labels: ["feature", "request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: example. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-feature
    attributes:
      label: Explanation of the feature
      description: Please explain the feature you are requesting and any specific use cases
      placeholder: The new feature description
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Relevant code
      description: |
        If applicable, please showcase how you intend the new feature to work in code.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
