# This workflow will validate if the changelog is updated

name: Ensure Changelog Updated

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-changelog-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for updated CHANGELOG
        run: |
          .github/scripts/check-changed-file.sh ${{ github.base_ref }} CHANGELOG.md

      - name: Get version
        id: get-version
        run: |
          VERSION=$(grep ^version pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Ensure CHANGELOG has entry for this version
        run: |
          .github/scripts/check-changelog-has-version.sh ${{ steps.get-version.outputs.version }}
