# This workflow will run unit tests on the code at pull request time

name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --extra test

      - name: Run PyTest
        run: |
          source .venv/bin/activate
          pytest

      - name: Run MyPy  # Typing Checking
        run: |
          source .venv/bin/activate
          mypy

      - name: Run Ruff  # Linting
        run: |
          source .venv/bin/activate
          ruff check src/

  run-python-tests-from-test-pypi:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Get version
        id: get-version
        run: |
          VERSION=$(grep ^version pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          uv sync --extra test
          uv pip uninstall package-name -y
          uv pip install --index-url https://test.pypi.org/simple/ package-name==$VERSION --system

      - name: Run PyTest
        run: |
          source .venv/bin/activate
          pytest --no-cov  # override
